services:
  postgres:
    image: postgres:latest
    container_name: osi_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - osi_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 5

  migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile.migrate
    container_name: osi_migrate
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} host=postgres port=${POSTGRES_PORT} sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
    command: [ "-dir", "./migrations", "up" ]
    networks:
      - osi_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: osi_backend
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      # Используем имена переменных из config.go
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=5432
      - BACKEND_PORT=8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - osi_network
    restart: unless-stopped

volumes:
  postgres_data:


networks:
  osi_network:
    driver: bridge

# Enter Postgress CLI
# docker exec -it osi_postgres psql -U POSTGRES_USER -d POSTGRES_DB
