services:
  postgres:
    image: postgres:17
    container_name: osi_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - osi_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 5

  migrate:
    image: golang:1.23-alpine
    container_name: osi_migrate
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      DB_DSN: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c " go install github.com/pressly/goose/v3/cmd/goose@latest && goose -dir ./migrations postgres \"$DB_DSN\" up "
    networks:
      - osi_network
    restart: no

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: osi_backend
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      # Используем имена переменных из config.go
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=5432
      - BACKEND_PORT=8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - osi_network
    restart: unless-stopped

volumes:
  postgres_data:


networks:
  osi_network:
    driver: bridge

# Enter Postgress CLI
# docker exec -it osi_postgres psql -U POSTGRES_USER -d POSTGRES_DB
