version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: osi_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESS_HOST_AUTH_METHOD: md5
