name: Go CI

on:
  push:
    branches:
      - main
      - dev
    paths:
      'backend/*'
  pull_request:
    branches:
      - main
      - dev
    paths:
      'backend/*'

jobs:
    backend:
        name: Run Backend
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up Golang
              uses: actions/setup-go@v5
              with:
                go-version: '>=1.22'

            - name: Download dependencies
              run: go mod download

            - name: Install swag
              run: go install github.com/swaggo/swag/cmd/swag@latest

            - name: Generate Swagger docs
              run: swag init -g cmd/main.go -o docs --parseDependency --parseInternal

            - name: Check Swagger docs are up to date
              run: |
                if [ -n "$(git status --porcelain docs/)" ]; then
                    echo "❌ Swagger documentation is out of date!"
                    echo "Run 'swag init -g cmd/main.go -o docs --parseDependency --parseInternal' and commit the changes"
                    git diff docs/
                    exit 1
                else
                    echo "✅ Swagger documentation is up to date"
                fi

            - name: Check formatting
              run: |
                    gofmt_out=$(gofmt -l .)
                    if [ -n "$gofmt_out" ]; then
                        echo "❌ The following files are not formatted:"
                        echo "$gofmt_out"
                        exit 1
                    else
                        echo "✅ All files are properly formatted"
                    fi

            - name: Static analisys
              run: go vet ./...
            
            - name: Run tests
              run: go test ./... -v -coverprofile=coverage.out
              working-directory: ./backend

            - name: Show coverage
              run: go tool cover -func=coverage.out
            
            - name: Generate HTML coverage report
              run: go tool cover -html=coverage.out -o coverage.html

            - name: Upload HTML report
              uses: actions/upload-artifact@v4
              with:
                name: coverage-report
                path: ./coverage.html
            

            
  